instance_groups:
- name: elasticsearch_master
  vm_type: t3.xlarge

- name: elasticsearch_data
  vm_type: r5.2xlarge
  update:
    max_in_flight: 2
    canaries: 2

- name: maintenance
  vm_type: t3.large

- name: redis
  vm_type: t3.medium

- name: archiver
  instances: 3
  vm_type: m5.xlarge
  jobs:
  - name: ingestor_cloudfoundry-firehose
    properties:
      cloudfoundry:
        api_endpoint: https://api.fr.ea.cloud.gov

- name: ingestor
  instances: 7
  vm_type: m5.2xlarge
  jobs:
  - name: ingestor_cloudfoundry-firehose
    properties:
      cloudfoundry:
        api_endpoint: https://api.fr.ea.cloud.gov

- name: kibana
  vm_type: t3.xlarge
  jobs:
  - name: kibana-auth-plugin
    properties:
      kibana-auth:
        cloudfoundry:
          api_endpoint: https://api.fr.ea.cloud.gov
          system_domain: fr.ea.cloud.gov
  - name: route_registrar
    consumes:
      nats-tls:
        from: nats-tls
        deployment: cf-easta
    properties:
      route_registrar:
        routes:
        - name: logsearch
          uris: [logs.fr.ea.cloud.gov]
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - deployment: cf-easta
          domain: bosh
          instance_group: nats
          network: default
          query: '*'

- name: smoke-tests
  vm_type: t3.small
  jobs:
  - name: smoke_tests
    properties:
      smoke_tests:
        count_test:
          run: true
          minimum: 100000
          time_interval: "5m"
          time_field: "@timestamp"
          index_pattern: "logs-app-*"


stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent
  version: latest
